apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-resource-quota
  namespace: ynishizaki-dev
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 10Gi
    limits.cpu: "4"
    limits.memory: 10Gi
