name: Deploy to OpenShift

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Get OpenShift Token
      id: get-token
      run: |
        TOKEN=$(oc create token github-actions-sa -n ynishizaki-dev)
        echo "::add-mask::$TOKEN"
        echo "OPENSHIFT_TOKEN=$TOKEN" >> $GITHUB_ENV


    - name: Log in to OpenShift 
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

    - name: Apply Manifest
      run: |
       oc apply -f ./manifests/
