name: policy-validation

env:
  OPENSHIFT_NAMESPACE: ${{ vars.OPENSHIFT_NAMESPACE }}

on:
  pull_request:
    paths:
      - '**/*.yaml'

jobs:
  validate:
    runs-on: self-hosted
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Get changed files
      id: changes
      run: |
        git fetch origin main
        git diff --name-only origin/main > changed.txt

    - name: Run conftest
      run: |
        actor="${{ github.actor }}"
        while IFS= read -r file; do
          if [[ "$file" == *.yaml || "$file" == *.yml ]]; then
            conftest test "$file" --input yaml --namespace ${{ env.OPENSHIFT_NAMESPACE }} --data <(echo '{"_user": "'"$actor"'"}')
          fi
        done < changed.txt