name: Create OpenShift Project

on:
  push:
    branches:
      - main  # mainブランチにpushされたときに実行

jobs:
  create_project:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up OpenShift CLI
      run: |
        curl -LO https://github.com/openshift/okd/releases/download/release-4.9.18/openshift-client-linux-4.9.18.tar.gz
        tar -xvzf openshift-client-linux-4.9.18.tar.gz
        sudo mv oc /usr/local/bin/
        oc version

    - name: Login to OpenShift
      run: |
        oc login https://<openshift-cluster-url> --token=${{ secrets.OPENSHIFT_TOKEN }}

    - name: Create OpenShift Project
      run: |
        oc new-project <project-name>
