name: Deploy to OpenShift

on:
  push:
    paths:
      - deployment.yaml
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login to OpenShift
      run: |
        oc login --server=${{ secrets.OPENSHIFT_SERVER }} \
          --token=${{ secrets.OPENSHIFT_TOKEN }} \
          --insecure-skip-tls-verify=true

    - name: Apply Manifest
      run: |
        oc project ${{ secrets.OPENSHIFT_NAMESPACE }}
        oc apply -f deployment.yaml
