name: Deploy to OpenShift

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up OpenShift CLI
      run: |
        curl -LO https://github.com/openshift/okd/releases/download/release-4.9.18/openshift-client-linux-4.9.18.tar.gz
        tar -xvzf openshift-client-linux-4.9.18.tar.gz
        sudo mv oc /usr/local/bin/
        oc version
        
    - name: Login to OpenShift
      run: |
        oc login --server=${{ secrets.OPENSHIFT_SERVER }} \
          --token=${{ secrets.OPENSHIFT_TOKEN }} \
          --insecure-skip-tls-verify=true

    - name: Apply Manifest
      run: |
        oc project ${{ secrets.OPENSHIFT_NAMESPACE }}
        oc apply -f deployment.yaml
